import { Card, CardGroup } from './types';

export const SHEET_API_URL = 'https://script.google.com/macros/s/AKfycbw5NVCqn797Q6hd2mGvgfGY3lAZdkmMrcmCPEojQ8XSJXcOOlgsuAZthhUDzKMDptlH/exec';

// Helper to generate consistent AI images based on prompts
const getImg = (prompt: string, seed: number) => 
  `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt + " tarot card style, mystical, magical, highly detailed, 8k, fantasy art, vertical aspect ratio")}?width=400&height=600&nologo=true&seed=${seed}`;

export const CARDS: Card[] = [
  // --- NHÓM 1: WINNERS (5%) ---
  {
    id: 'rich-kid',
    name: 'THE RICH KID',
    title: 'ÔNG HOÀNG TIỀN BẠC',
    imageSeed: 101,
    imageUrl: getImg('King sitting on pile of gold coins, luxury, crown, wealth, golden light', 101),
    group: CardGroup.WINNER,
    flavor: 'Dừa Non hoặc Bơ Sáp',
    message: "TING TING! 💰 Vũ trụ vừa chuyển khoản cho bạn một sự may mắn khổng lồ. Năm nay 'ngồi mát ăn bát vàng', tiền vào như nước.",
    advice: "Để ăn mừng sự giàu sang sắp tới, Baby Boss xin mời bạn 1 viên kem Dừa Non béo ngậy. Ăn ngay cho tiền về ví!",
    color: 'bg-yellow-400',
  },
  {
    id: 'lovers',
    name: 'THE LOVERS',
    title: 'KẺ SI TÌNH',
    imageSeed: 102,
    imageUrl: getImg('Romantic couple holding hands, roses, heart, love, pink and red atmosphere', 102),
    group: CardGroup.WINNER,
    flavor: 'Dâu Tây (Strawberry)',
    message: "Chúc mừng! ❤️ Vận đào hoa của bạn năm nay đỏ rực rỡ. Người ấy đang ở rất gần rồi, đừng tìm kiếm đâu xa.",
    advice: "Vũ trụ muốn bạn ngọt ngào hơn để đón tình yêu, nên tặng ngay 1 viên Gelato Dâu Tây. Ăn đi cho đời thêm thắm!",
    color: 'bg-red-400',
  },
  {
    id: 'fool',
    name: 'THE FOOL',
    title: 'KHỞI ĐẦU MỚI',
    imageSeed: 103,
    imageUrl: getImg('Young joyful traveler walking towards sun, white dog, cliff edge, freedom, bright sky', 103),
    group: CardGroup.WINNER,
    flavor: 'Vani (Vanilla)',
    message: "Bạn bốc được lá bài của sự may mắn thuần khiết! Mọi xui xẻo cũ đã qua, một chương mới rực rỡ đang mở ra.",
    advice: "Như một món quà khích lệ cho hành trình mới, Baby Boss tặng bạn 1 viên Vani ngọt ngào. Hãy cứ vô tư, đời sẽ ưu ái bạn!",
    color: 'bg-blue-300',
  },
  // --- NHÓM 2: MANIFEST (95%) ---
  {
    id: 'slay-queen',
    name: 'THE SLAY QUEEN',
    title: 'THẦN THÁI',
    imageSeed: 201,
    imageUrl: getImg('Powerful queen on throne, glowing aura, confident, fashion, sharp gaze, luxury', 201),
    group: CardGroup.MANIFEST,
    flavor: 'Sầu Riêng',
    message: "Lá bài nói rằng hào quang của bạn đang bị... tắc nghẽn một chút. Muốn năm nay 'Slay' banh nóc, ai nhìn cũng nể thì phải nạp ngay sự 'nặng đô' vào người.",
    advice: "👉 Order ngay 1 viên Sầu Riêng để buff 200% công lực thần thái. Ăn xong đảm bảo không ai dám xem thường!",
    color: 'bg-yellow-600',
  },
  {
    id: 'healing',
    name: 'THE HEALING',
    title: 'CHỮA LÀNH',
    imageSeed: 202,
    imageUrl: getImg('Peaceful nature, lotus flower, green light, meditation, calm water, healing energy', 202),
    group: CardGroup.MANIFEST,
    flavor: 'Trà Xanh (Matcha)',
    message: "Vũ trụ thấy tâm bạn đang động, deadline dí, drama vây quanh. Bạn cần thanh lọc gấp! Đừng để sự tiêu cực đeo bám sang năm mới.",
    advice: "👉 Hãy dùng ngay 1 viên Matcha thanh mát để 'rửa trôi' muộn phiền. Ăn một miếng, tâm tịnh lại, vận may mới tới được!",
    color: 'bg-green-500',
  },
  {
    id: 'drama',
    name: 'THE DRAMA',
    title: 'THỊ PHI',
    imageSeed: 203,
    imageUrl: getImg('Stormy sea, swords clashing, shield, protection, intense atmosphere, orange and black', 203),
    group: CardGroup.MANIFEST,
    flavor: 'Chanh Muối hoặc Rum Nho',
    message: "Cẩn thận! Có kẻ đang ghen ăn tức ở, muốn lôi bạn vào thị phi. Muốn 'miễn nhiễm' với drama? Bạn cần một chút vị mặn mòi, cay nồng để át vía tiểu nhân.",
    advice: "👉 Gọi ngay vị Chanh Muối/Rum Nho. Vị kem này là 'tấm khiên' bảo vệ bạn khỏi những lời khẩu nghiệp đấy!",
    color: 'bg-orange-400',
  },
  {
    id: 'hustler',
    name: 'THE HUSTLER',
    title: 'CÀY CUỐC',
    imageSeed: 204,
    imageUrl: getImg('Busy merchant with bags of money, clock, working hard, gears, industrial, coffee beans', 204),
    group: CardGroup.MANIFEST,
    flavor: 'Cafe hoặc Socola Đắng',
    message: "Sắp tới là cơ hội thăng tiến ngàn năm có một, nhưng bạn phải cực kỳ tỉnh táo để nắm bắt. Đừng ngủ gật trên chiến thắng!",
    advice: "👉 Nạp ngay 1 viên Cafe/Socola Đắng. Vị đắng này sẽ giúp bạn bừng tỉnh và 'hốt trọn' hợp đồng lớn. Đầu tư cho bản thân 1 viên kem để đổi lấy thành công, quá hời!",
    color: 'bg-gray-800',
  },
  {
    id: 'ghost',
    name: 'THE GHOST',
    title: 'MẬP MỜ',
    imageSeed: 205,
    imageUrl: getImg('Foggy forest, mysterious silhouette, moon, mint leaves, cold blue light, ethereal', 205),
    group: CardGroup.MANIFEST,
    flavor: 'Bạc Hà (Mint)',
    message: "Chuyện tình cảm mập mờ như sương khói làm bạn mệt mỏi? Bạn cần một cái đầu lạnh để đưa ra quyết định sáng suốt.",
    advice: "👉 Hãy thử vị Bạc Hà lạnh tê. Sự the mát này sẽ giúp bạn 'tỉnh mộng' và dứt khoát hơn. Ăn xong tự khắc biết nên giữ hay buông!",
    color: 'bg-teal-400',
  },
  {
    id: 'flex',
    name: 'THE FLEX',
    title: 'KHOE KHOANG',
    imageSeed: 206,
    imageUrl: getImg('Peacock spreading feathers, spotlight, diamond, glowing sun, mango fruit, vibrant yellow', 206),
    group: CardGroup.MANIFEST,
    flavor: 'Xoài (Mango)',
    message: "Năm nay là năm tỏa sáng, nhưng hiện tại năng lượng của bạn hơi... chìm. Muốn thu hút mọi ánh nhìn, bạn cần màu vàng rực rỡ của mặt trời.",
    advice: "👉 Múc ngay 1 viên Kem Xoài. Vị chua ngọt này sẽ kích hoạt hào quang, giúp bạn đi đâu cũng là trung tâm vũ trụ (Spotlight)!",
    color: 'bg-yellow-500',
  },
  {
    id: 'balance',
    name: 'THE BALANCE',
    title: 'CÂN BẰNG',
    imageSeed: 207,
    imageUrl: getImg('Scales of justice balancing sun and moon, yin yang, harmony, cheese block, calm sky', 207),
    group: CardGroup.MANIFEST,
    flavor: 'Phô Mai (Cheese) hoặc Việt Quất',
    message: "Cuộc sống đang hơi chao đảo đúng không? Lúc thì vui quá, lúc lại buồn thiu. Bạn cần sự cân bằng giữa mặn và ngọt, giữa cảm xúc và lý trí.",
    advice: "👉 Vị Phô Mai là chìa khóa. Sự kết hợp mặn-béo này sẽ giúp tâm trạng bạn ổn định lại. Ăn đi rồi mọi chuyện sẽ đâu vào đấy!",
    color: 'bg-orange-200',
  },
  {
    id: 'mystery',
    name: 'THE MYSTERY',
    title: 'BÍ ẨN',
    imageSeed: 208,
    imageUrl: getImg('Crystal ball, third eye, galaxy, purple smoke, tarot cards, magic, blueberries', 208),
    group: CardGroup.MANIFEST,
    flavor: 'Khoai Môn hoặc Việt Quất',
    message: "Trực giác mách bảo bạn sắp tìm ra một bí mật quan trọng hoặc một ý tưởng triệu đô. Nhưng bạn cần sự tĩnh lặng để 'bắt sóng' vũ trụ.",
    advice: "👉 Hãy chọn vị Khoai Môn/Việt Quất. Sắc tím huyền bí này sẽ khai mở giác quan thứ 6 của bạn. Đừng bỏ lỡ tín hiệu này!",
    color: 'bg-purple-600',
  },
  {
    id: 'yolo',
    name: 'THE YOLO',
    title: 'TRẢI NGHIỆM',
    imageSeed: 209,
    imageUrl: getImg('Backpack traveler, fireworks, open road, passion fruit, energy, explosion of colors', 209),
    group: CardGroup.MANIFEST,
    flavor: 'Chanh Dây (Passion Fruit)',
    message: "Cuộc đời quá ngắn để sống nhạt nhòa! Vũ trụ đang thúc giục bạn bước ra khỏi vùng an toàn. Bạn cần một cú hích đầy năng lượng.",
    advice: "👉 Chanh Dây là lựa chọn định mệnh. Vị chua bùng nổ này sẽ kích thích máu phiêu lưu trong bạn. Ăn xong là muốn xách ba lô lên và đi ngay!",
    color: 'bg-yellow-300',
  },
];